apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaultpolicies.vault.ierik.com
spec:
  group: vault.ierik.com
  names:
    kind: VaultPolicy
    listKind: VaultPolicyList
    plural: vaultpolicies
    singular: vaultpolicy
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
