---
- name: Get root token
  community.kubernetes.k8s_info:
    kind: Secret
    namespace: "{{ namespace }}"
    name: vault-root-token
  register: vault_root_token_secret
  when: vault_root_token is undefined

- name: Set root token
  set_fact:
    vault_root_token: "{{ vault_root_token_secret.resources[0].data.token|b64decode }}"
  when: 
    - vault_root_token_secret.resources is defined
    - vault_root_token_secret.resources|length > 0

- name: Login
  community.kubernetes.k8s_exec:
    namespace: "{{ namespace }}"
    pod: vault-0
    command: "vault login {{ vault_root_token }}"
  changed_when: false

- name: Enable K8S auth
  hashivault_auth_method:
    token: "{{ vault_root_token }}"
    url: "{{ lookup('env','VAULT_ADDR')|default(vault_url,true) }}"
    method_type: kubernetes
  register: enable_k8s_auth

- name: Config K8S auth
  community.kubernetes.k8s_exec:
    namespace: "{{ namespace }}"
    pod: vault-0
    command: |
      /bin/sh -c 'vault write auth/kubernetes/config \
      token_reviewer_jwt=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) \
      kubernetes_host=https://${KUBERNETES_PORT_443_TCP_ADDR}:443 \
      kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
  changed_when: enable_k8s_auth.changed

- name: Set vault-operator policy
  hashivault_policy:
    token: "{{ vault_root_token }}"
    url: "{{ lookup('env','VAULT_ADDR')|default(vault_url,true) }}"
    name: vault-operator
    rules: "{{ lookup('file','vault-operator.hcl') }}"

- name: Set vault-operator role
  hashivault_k8s_auth_role:
    token: "{{ vault_root_token }}"
    url: "{{ lookup('env','VAULT_ADDR')|default(vault_url,true) }}"
    name: vault-operator
    policies: ["vault-operator"]
    bound_service_account_names: ["vault-operator"]
    bound_service_account_namespaces: ["{{ lookup('env','OPERATOR_NAMESPACE')|default('vault-operator',true) }}"]

- name: Logout
  community.kubernetes.k8s_exec:
    namespace: "{{ namespace }}"
    pod: vault-0
    command: "rm /home/vault/.vault-token"
  changed_when: false